/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 10-08-2020
 * @last modified by  : Nicholas Glesmann
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   07-15-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class MyClass {
    public static void myMethod()
    {
        System.debug('Hello World17');
    }
    
    public static void myMethod2()
    {
        System.debug('Hello World17');
    }

    public static void myMethod3()
    {
        System.debug('Hello World17');
    }
}